### ISSUE TITLE
Failed to download repo vuejs-templates/vue-webpack-chrome-extension-template: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by yaadyaad** [ALiangLiang/vue-webpack-chrome-extension-template#1]
Hi,
Initialization of the new project that was shown on the main page does not work.
`vue init vue-webpack-chrome-extension-template my-project`
   
`vue-cli · Failed to download repo vuejs-templates/vue-webpack-chrome-extension-template: Response code 404 (Not Found)`

Adding ALiangLiang/ before the template name - works fine:
`vue init ALiangLiang/vue-webpack-chrome-extension-template my-project
`

**Comment by ALiangLiang** [comment]
Thanks for your report. Already update README.
