### ISSUE TITLE
Uses unsafe-eval

### ISSUE THREAD

**Issue by torarnv** [ALiangLiang/vue-webpack-chrome-extension-template#2]
Would be nice with an unsafe-eval free version, both Vue and webpack should support it.

**Comment by ALiangLiang** [comment]
OK. I found which option causing CSP error. 
```
    devtool: '#cheap-module-eval-source-map',
```
It shouldn't use cheap-module-"eval"-source-map.

**Comment by torarnv** [comment]
Thanks!! :)

**Comment by sinchang** [comment]
thanks your issue!!! 👍
